prFirstTimeContributor: Welcome to the Kogito Community!. Please make sure you've read the [contributors' guide](README.md#contributing-to-kogito-images-repository)

prCiTrigger: Jenkins test this

prEdit: Change detected in the PR, requesting reviews and running pipeline(if required) again

prReopen: PR reopened. requesting reviews and running pipeline(if required) again