name: Run S2I modules Bats Tests

on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils --fix-missing
      - name: Cache bats binaries
        uses: actions/cache@v1
        with:
          path: $GITHUB_WORKSPACE/bats/
          key: ${{ runner.os }}-bats-binaries
          restore-keys: |
            ${{ runner.os }}-bats-binaries
      - name: run bats
        run: |
          ./script/run-bats.sh